services:
  - type: web
    name: aporte-capital
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: EMAIL_USER
        value: bragasan34@gmail.com
      - key: EMAIL_PASS
        sync: false
      - key: RECIPIENT_EMAIL
        value: bragasan1@yahoo.com.br
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: ALLOWED_FILE_TYPES
        value: application/pdf,image/jpeg,image/png
      - key: WHATSAPP_NUMBER
        value: 5592999889392
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
    healthCheckPath: /
    autoDeploy: true